name: Release

on:
  push:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Create tar file
        run: zip -r -j linux-fonts.zip \
            CascadiaCode \
            FiraCode \
            FiraMono \
            FiraSans \
            GitLabMono \
            GitLabSans \
            Hack \
            Inter \
            Iosevka \
            JetBrainsMono \
            Roboto \
            RobotoMono \
            SourceCodePro \
            UbuntuSans \
            UbuntuSansMono

      - uses: "marvinpinto/action-automatic-releases@v1.2.1"
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          automatic_release_tag: "latest"
          prerelease: false
          title: latest
          files: |
            linux-fonts.zip
