name: Release

on:
  push:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Update dependencies
        run: sudo apt update

      - name: Create dist folder
        run: mkdir dist

      - name: Move font
        run: |
          mv CascadiaCode/*.ttf dist
          mv FiraCode/*.ttf dist
          mv FiraMono/*.ttf dist
          mv FiraSans/*.ttf dist
          mv GitLabMono/*.ttf dist
          mv GitLabSans/*.ttf dist
          mv Hack/*.ttf dist
          mv Inter/*.ttf dist
          mv JetBrainsMono/*.ttf dist
          mv Roboto/*.ttf dist
          mv RobotoMono/*.ttf dist
          mv SourceCodePro/*.ttf dist
          mv UbuntuSans/*.ttf dist

      - name: Create tar file
        run: cd dist && tar -czvf linux-fonts.tar *.*

      - uses: "marvinpinto/action-automatic-releases@v1.2.1"
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          automatic_release_tag: "latest"
          prerelease: false
          title: latest
          files: |
            dist/linux-fonts.tar
